### ISSUE TITLE
可以使用 BGmi 代替下载订阅的步骤

### ISSUE THREAD

**Issue by kahosan** [EstrellaXD/Bangumi_Auto_Collector#1]
如标题所说，订阅下载功能这块完全可以交给 [BGmi](https://github.com/BGmi/BGmi) 这个项目，然后再适配导入 Plex 等媒体服务器

**Comment by EstrellaXD** [comment]
2.0 版本已经初步开发完成，相比 BGmi 更好上手操作更加简单 [https://github.com/EstrellaXD/Bangumi_Auto_Collector#全自动追番机](url)
