### ISSUE TITLE
bug反馈 番名含特殊字符

### ISSUE THREAD

**Issue by HoliaMagirl** [EstrellaXD/Bangumi_Auto_Collector#4]
环境：arm64（树莓派4b）
  ab版本：V2.2.8
  qb版本：4.4.1

部分番名含特殊字符而导致创建文件夹失败
 如：
Boruto: Naruto Next Generations   的【: 】
Komi-san wa, Komyushou Desu.    的【.】

**Comment by EstrellaXD** [comment]
19bc49a8c92f806698063910cb3eca50018c9a26 已经修复
